### ISSUE TITLE
Reduce of empty array with no initial value in piechart (Donut)

### ISSUE THREAD

**Issue by PROda221** [Abhinandan-Kushwaha/react-native-gifted-charts#169]
Hello! 
My donut chart use to work before (on version 1.0.16) but now sending in the same type of data gives me "Reduce of empty array with no initial value" error. 

my Data: 
![image](https://user-images.githubusercontent.com/31884259/165301241-acad0635-0856-45bc-bf38-33ca83974e4f.png)

I can't revert to previous versions now since new features are needed in my project. Is anything possible?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋
Thanks for pointing out the issue. It has been fixed in version `1.2.12`🎉

**Comment by NemyaNation** [comment]
Hey @Abhinandan-Kushwaha 

Still seeing a similar error on `"react-native-gifted-charts": "^1.2.17",`

`Array.prototype.reduce() requires an initial value with empty array`

**Comment by f-bog** [comment]
Still getting this issue on` 1.4.7`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @slaneyrw @f-bog @aymenbuu @PROda221 , Thanks for raising this issue. This has now been fixed from versions `1.4.69` onwards. Please use the latest version of the library.
