### ISSUE TITLE
pointerConfig on AreaGraph (Android)

### ISSUE THREAD

**Issue by PROda221** [Abhinandan-Kushwaha/react-native-gifted-charts#177]
Hello! 
The Android integration for pointerConfig is quite jaggy 
When will that be fixed?

**Comment by PROda221** [comment]
Any update on this?

**Comment by Abhinandan-Kushwaha** [comment]
Not yet @PROda221 
Will try to fix it and release an update by this weekend.

**Comment by PROda221** [comment]
Looking forward to it! Hoping for the best this weekend👍

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋
The issue has been resolved in version `1.2.18`🎉
Cheers!🍺

**Comment by PROda221** [comment]
Hello @Abhinandan-Kushwaha,
I added the updated library to my project but the problem still persists. Let me attach a video here: 

https://user-images.githubusercontent.com/31884259/168488626-1dc0adfe-68cd-49ac-bb05-63eea9abb99b.mp4

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 
The issue on Android no more exists if you set `autoAdjustPointerLabelPosition` to false.
When `autoAdjustPointerLabelPosition` is true, it's still jaggy on Android.

Will look into it soon.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 
Yes, the issue still persists, but it's much better than the previous video.
And this seems to be an issue with Android itself. I am still working on this. Hoping to get it fixed in 1-2 weeks.

**Comment by PROda221** [comment]
Oh ok got it. Thanks. 
Waiting on the fix <3

**Comment by PROda221** [comment]
Any updates?

**Comment by MollieRick** [comment]
@Abhinandan-Kushwaha Same here, is there already an fix or workaround after such a time? :)

**Comment by tahaipek** [comment]
Any updates for this situation?

**Comment by ushan-swivel** [comment]
any update still having the same issue

**Comment by rodrigolourenco** [comment]
Hey, any news on this issue?

**Comment by loc-nguyenthien** [comment]
> Hey, any news on this issue?
> 
> Researching a bit more this seems to be connected with this RN issue: [facebook/react-native#31843](https://github.com/facebook/react-native/issues/31843)
> 
> Some proper rewrite might be need on the lineChart side

Hi guys, with the issue share by @rodrigolourenco, I did some research and testing and found a way to fix this.

So I notice that the issue in Android is that when our pointer (finger touch) hit the Label component. The `GestureEvent` location will be relative to that Label and no longer relative to our chart. So I set the `pointerEvent` of my Label component to `none` and now the issue is gone.

You guys can checkout the video I attached below

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/114563576/a95b6289-7285-4935-a4b0-38e26a169887

**Comment by loc-nguyenthien** [comment]
Sometime the flicker event still happen, I noticed the same issue above also occur when our finger touch the `pointer` (usually the pointer dot in LineChart) so you will need to make a patch to remove `pointerEvent` for the pointer of the chart as below

![Screenshot 2023-10-24 at 14 46 56](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/114563576/a5ab0f2a-46e8-4040-a140-d7d822666b70)

FYI: I use verion `1.3.11`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @loc-nguyenthien 👋
Kudos to your research and thanks a ton! This actually solved the problem. I have added `pointerEvents='none'` as per your suggestion and it works like a charm 🎉
 
Fixed in version `1.3.12`

**Comment by loc-nguyenthien** [comment]
Hi @Abhinandan-Kushwaha 
I should be thankful for your library  🎉 And just to be sure, since we are allowed other to add their own customize `pointerLabelComponent`, I think we should note this into the document (i.e. in Common issues) so that other will notice this

**Comment by Abhinandan-Kushwaha** [comment]
@loc-nguyenthien 
I will make this update. Thanks again!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @loc-nguyenthien 👋
I have added`pointerEvents='none' as per your suggestion in version `1.3.13`
