### ISSUE TITLE
Issue with eslint - tsc

### ISSUE THREAD

**Issue by hichemBAALI** [Abhinandan-Kushwaha/react-native-gifted-charts#222]
Hi,
There are some errors that you are ignored which appears when someone is using ts in strict mode. Please, could you just take a look on that.

here an example of what I am getting

```
node_modules/react-native-gifted-charts/src/LineChart/index.tsx:3360:21 - error TS6133: 'item' is declared but its value is never read.

3360           data.map((item: itemType, index: number) => {
                         ~~~~

```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @hichemBAALI 👋
The issue is fixed in version `1.2.33`🎉

**Comment by hichemBAALI** [comment]
> Hi @hichemBAALI 👋 The issue is fixed in version `1.2.33`🎉

Hi again, I forgot to thank you about this library it helped a lot.
Unfortunately, the problem still persisting. If you're using Typescript, please try to run `yarn tsc -noEmit` to see what is the problem


`    The expected type comes from property 'gradientCenterColor' which is declared here on type 'itemType'

node_modules/react-native-gifted-charts/src/PieChart/main.tsx:12:22 - error TS7016: Could not find a declaration file for module './colors'. '/Users/mac/Work/Tulix-Tech/Tulix-App/mobile-app-v2/node_modules/react-native-gifted-charts/src/PieChart/colors.js' implicitly has an 'any' type.

12 import {colors} from './colors';
                        ~~~~~~~~~~

node_modules/react-native-gifted-charts/src/PieChart/main.tsx:84:9 - error TS7034: Variable 'data' implicitly has type 'any[]' in some locations where its type cannot be determined.

84   const data = [];
           ~~~~

node_modules/react-native-gifted-charts/src/PieChart/main.tsx:254:17 - error TS7005: Variable 'data' implicitly has an 'any[]' type.

254                 data[0].onPress
                    ~~~~`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @hichemBAALI 
Glad to know that you liked the library.
I will fix the `type` issues in a few days, running short of time currently.

**Comment by kale1d** [comment]
is there any workaround?
