### ISSUE TITLE
Error when all the data values in line chart is 0.

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#58]
[{"label": "Jan",, "value": 0}, {"label": "Feb", "value": 0}, {"label": "Mar", "value": 0}]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋

Thanks a lot for pointing out this bug.

The issue is now fixed in version `0.2.5` 🎉

Please update to version `0.2.5` and run again.

**Comment by mehdinourollah** [comment]
I still have this issue in `"react-native-gifted-charts": "^1.2.31"` 

Data :
 `const inbound_all_data = [
        { value: 0, label: 'test' },
        { value: 0, label: 'test2' }
    ]`
Chart:
`   <PieChart  radius={60} innerRadius={40} data={inbound_all_data} donut={true} />`
