### ISSUE TITLE
How to create group bar chart (Left Y-Axis) and 2 line chart (Right Y-axis) with negative values

### ISSUE THREAD

**Issue by sandeep-synclovis** [Abhinandan-Kushwaha/react-native-gifted-charts#814]
<img width="286" alt="65QV3hSB" src="https://github.com/user-attachments/assets/b2799aeb-f3e2-46a3-bea5-d1a038cf4ecb">

I want to create a graph as same to the above image where we have a group bar connected with the left Y-axis and 2 two-line graphs connected with the right Y-axis, I can achieve this if all the values are positive, but face a challenge where values are negative.

When trying I am getting it like the below image.

<img width="283" alt="VCZUljrt" src="https://github.com/user-attachments/assets/aa45a9d8-f7fc-4106-ba66-ebf3727c246f">

1. Lines are not aligned with the right Y-axis
2. The right Y-Axis is not showing values correctly(it supposed to show 50, 25, 0, -25).

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis Can you share the code and data?

**Comment by sandeep-synclovis** [comment]
Hi @Abhinandan-Kushwaha ,

I am sharing a pdf doc with data and code.

[Data And Barchart Code.pdf](https://github.com/user-attachments/files/16861681/Data.And.Barchart.Code.pdf)
.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis I have fixed the positioning of the Lines and the secondary Y-axis labels. The fixes are available from version `1.4.32` onwards.

Also, in your code you are passing a negative value to the `negativeStepValue` prop. You are not supposed to pass a negative value here, but a positive value (just remove `* -1` from your code). Same for the secondary Y-axis.

Please use the latest version of the library.

**Comment by sandeep-synclovis** [comment]
Hi, Thanks for the changes and quick update, but still my issue related to the right Y-Axis is not resolved.

If you observe shared screenshots, the first value on the right Y-axis should be 3000 but it's showing -1500
here for right YAxis, I am passing [3000, 1500, 0, -1500]

<img width="282" alt="Screenshot 2024-09-05 at 12 44 12 PM" src="https://github.com/user-attachments/assets/2d28c800-5856-43fb-af25-51133c9d280c">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis 
Thanks for reporting this issue. It has been fixed from versions `1.4.33` onwards. 🎉

Please use the latest version of the library.

**Comment by sandeep-synclovis** [comment]
Hi @Abhinandan-Kushwaha,

Thanks for the updates, but still right Y-Axis is not showing correctly. It's fine if both left & right y-Axis have one negative value. But if we have only one axis with a negative value it's not showing correctly

1. 
<img width="279" alt="Screenshot 2024-09-09 at 1 29 18 PM" src="https://github.com/user-attachments/assets/269ca26c-288f-4126-b9b0-d8e8b7fbb85b">

Here, the left axis has a negative value but the right axis is all positive. In this, it's showing 2000 two times & 0 is not coming we make hideOrigin false.

2. 
<img width="280" alt="Screenshot 2024-09-09 at 1 32 17 PM" sr
<img width="280" alt="Screenshot 2024-09-09 at 1 35 37 PM" src="https://github.com/user-attachments/assets/6b409e0d-07a1-4c40-ab84-d51c1814a6e9">
c="https://github.com/user-attachments/assets/98f3df32-49a4-4ef1-b294-6e809ad6a9e4">

Here, both the left & right axes are correct. because both have one negative value.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis Thanks for reporting this bug. It has been fixed from versions `1.4.34` onwards.
Please use the latest version of the library.

**Comment by sandeep-synclovis** [comment]
Hi, @Abhinandan-Kushwaha Thanks for the update but the above issue is still not fixed.

**Comment by sandeep-synclovis** [comment]
Hi, @Abhinandan-Kushwaha/react-native-gifted-charts
***@***.***>, Thanks for the update but
the above issue is still not resolved.

Please let me know if we can connect via Zoom, Google Meet or any other
way, to go through this issue and resolve this issue.

*With Best Regards,*
*Sandeep Mishra*
Lead Software Engineer
Synclovis Systems Pvt. Ltd. <https://www.synclovis.com/> | Bluewings
<http://www.bluewings.in/>
Phone: +91 9620971846, +91 7892633810
Locations: Bangalore | New Jersey

**Comment by Abhinandan-Kushwaha** [comment]
We can connect over Google Meet. Please ping when you are available.
https://meet.google.com/scm-jogb-tsr

**Comment by sandeep-synclovis** [comment]
Hi, Please let me know if we can connect at 3:00 PM.

*With Best Regards,*
*Sandeep Mishra*
Lead Software Engineer
Synclovis Systems Pvt. Ltd. <https://www.synclovis.com/> | Bluewings
<http://www.bluewings.in/>
Phone: +91 9620971846, +91 7892633810
Locations: Bangalore | New Jersey

**Comment by Abhinandan-Kushwaha** [comment]
Please join

**Comment by Abhinandan-Kushwaha** [comment]
I am online. Can you join now?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis 
I have made fixes related to the secondary Y-axis and negative labels for the secondary Y-axis. Can you try again with the latest version of the library?

As per our discussion, you need the secondary Y-axis to have the 0 value below the Y-axis. For this, you can use the property `yAxisOffset` inside the `secondaryYAxis` object.

The `yAxisOffset` inside secondaryYAxis should be the value on the secondary Y-axis that coincides with the Y-axis.

Here's an example-

```js
onst data = [
  {value: 10},
  {value: 7},
  {value: -9},
  {value: 9},
  {value: 14},
  {value: -7},
  {value: 12},
];

const lData = [
  {value: 0},
  {value: 0.2},
  {value: 0.4},
  {value: -0.06},
  {value: 0.5},
  {value: -0.14},
  {value: 0.65},
];

return (
  <BarChart
    data={data}
    barWidth={15}
    spacing={15}
    frontColor={'rgba(50,100,50,0.5)'}
    showLine
    lineData={lData}
    lineConfig={{isSecondary: true, spacing: 15}}
    secondaryYAxis={{
      yAxisOffset: 0.14,
      noOfSectionsBelowXAxis: 5,
    }}
  />
);
```

The output of the above code is-

<img width="306" alt="Screenshot 2024-09-13 at 2 51 49 AM" src="https://github.com/user-attachments/assets/8e3c01c7-7493-4eec-9212-95e3f54e8675">

Please use the latest version of the library.

**Comment by sandeep-synclovis** [comment]
Hi,

I checked the solution you shared with me, but unfortunately, your solution
didn't work. It somehow managed to set the Y-axis (not exactly how I
wanted) but the line or bar chart was not aligned with the Y-axis. It will
be good if we get the left & right axis alignment separately (If possible
please look into this).

Thanks

*With Best Regards,*
*Sandeep Mishra*
Lead Software Engineer
Synclovis Systems Pvt. Ltd. <https://www.synclovis.com/> | Bluewings
<http://www.bluewings.in/>
Phone: +91 9620971846, +91 7892633810
Locations: Bangalore | New Jersey

**Comment by sandeep-synclovis** [comment]
Hi,

For now, I am setting both the right & left y-axis as negative if any of the axes is negative. But it will be very helpful if we get this feature in future where we can set one y-axis minimum value as negative & one-axis minimum value as 0 or positive.
