### ISSUE TITLE
Different behavior every time the onPress method is used in the pieChart

### ISSUE THREAD

**Issue by Nacho23** [Abhinandan-Kushwaha/react-native-gifted-charts#852]
### Description

I have been using the library for around 2 months and never had an issue, but today, without making any changes, the behavior of the onPress prop is acting strange. The first time it returns the item without any problem, but when I press it again, it returns an object like:

peripheral: true
strokeWidth: 0
value: 84.82 // the value keeps changing

And it keeps alternating like this, one time it works fine, and the next time it returns this object.
I'm not sure if it’s a version bug or what could have happened.

Could you help me? Thank you very much.

my code is:

  ```
const handlePress = (item: PieChartData) => {
    const updatedData = pieData.map((element) => ({
      ...element,
      focused: element.id === item.id,
    }));
    setPieData(updatedData);
  };
```

```
<PieChart
    data={pieData}
    donut
    showGradient
    sectionAutoFocus
    radius={90}
    innerRadius={60}
    isAnimated
    animationDuration={500}
    onPress={(item) => handlePress(item)}
    centerLabelComponent={() => {
      const focusedItem = pieData.find(item => item.focused);
      return (
        <>
          {focusedItem &&
            <View className="w-full justify-center items-center">
              <Text className="text-xl text-black font-bold">
                {focusedItem ? `${focusedItem.value}%` : ''}
              </Text>
              <FormattedText
                text={String(focusedItem?.amount)}
                format={'monetary'}
                decimals={0}
                classes="font-normal mb-1"
              />
              <Text className="px-3 w-full font-normal" adjustsFontSizeToFit numberOfLines={1} style={{ color: colors.gray }}>
                {focusedItem?.name}
              </Text>
            </View>
          }
        </>
      );
    }}
  />
```

### Steps to reproduce

1. Just press on label

### version of react-native-gifted-charts

1.4.41

### React Native version

0.74.5

### Platforms

Android, iOS

### Workflow

None

**Comment by patelkhushal** [comment]
I am also facing the same issue. Is there any workaround or plans to add a fix?

**Comment by Abhinandan-Kushwaha** [comment]
It’s an old issue which has been fixed now. Please use the latest version of the library.

See [v1.4.39](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/release-notes/release-notes.md#-1439)

**Comment by patelkhushal** [comment]
@Abhinandan-Kushwaha I am on 1.4.47 and still seeing this issue

**Comment by Abhinandan-Kushwaha** [comment]
I will test and let you know by tomorrow.

**Comment by Abhinandan-Kushwaha** [comment]
@patelkhushal This happens only when `focusOnPress` is set to true. It can be avoided by setting it to false.
