### ISSUE TITLE
App crashes when extrapolateMissingValue is set to false and only the last value is defined

### ISSUE THREAD

**Issue by dannybit** [Abhinandan-Kushwaha/react-native-gifted-charts#871]
### Description

When `extrapolateMissingValues` is set to false, `interpolateMissingValues` is set to true and `curved` is set to true, if the last item in the data list is defined but all other values are undefined the app crashes with the following error

<img width="415" alt="Screenshot 2024-10-13 at 11 44 36 PM" src="https://github.com/user-attachments/assets/5536a13d-adac-421d-81ea-8deaf540f7f9">

### Steps to reproduce

You can reproduce the issue by using the following LineChart component
Changing one of the values from undefined to a number resolves the issue.
```
<LineChart
  interpolateMissingValues={true}
  extrapolateMissingValues={false}
  data={[
    { value: undefined },
    { value: undefined },
    { value: 150 },
  ]}
  curved={false}
/>
```

### version of react-native-gifted-charts

1.4.43

### React Native version

0.74.3

### Platforms

iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dannybit 👋
Thanks for reporting the issue. It has been fixed from versions `1.4.45` onwards.

Please use the latest version of the library.

**Comment by dannybit** [comment]
Awesome thank you!

**Comment by greatnonso7** [comment]
@Abhinandan-Kushwaha I have updated to the latest version but I am still experiencing this error
