### ISSUE TITLE
Strip overlaps datapoints on multiline LineGraph

### ISSUE THREAD

**Issue by litofish** [Abhinandan-Kushwaha/react-native-gifted-charts#877]
### Description

Hi! 

I've been on version 1.3.11 for a while now and am trying to upgrade to the latest version (1.4.45) and am noticing a regression where the strip shown on focus is showing on top of data points / lines when there is more than 1 line shown on the graph. It seems to always overlap all but the last set of data points passed in. This was not happening in the previous version I was on.

<img width="403" alt="Screenshot 2024-10-20 at 10 04 39 PM" src="https://github.com/user-attachments/assets/6277d8c0-8704-491c-974b-e3b66d39ab5b">

### Steps to reproduce

Here is a slimmed down version of the relevant props I am passing in for the datasets and strip

```
     <LineChart
        // data points
        data: dataSets[0],
        data2: dataSets.length > 1 ? dataSets[1] : undefined,
        data3: dataSets.length > 2 ? dataSets[2] : undefined,
        thickness={3}
        // spacing
        width={graphWidth}
        height={graphHeight}
        endSpacing={10}
        // animation
        isAnimated
        scrollToEnd
        // axes
       ...
        // focus
        focusEnabled
        unFocusOnPressOut={false}
        showStripOnFocus
        stripHeight={stripHeight}
        stripWidth={3}
        onFocus={(item: NativeDataItem) => {
          setState(item);
        }}
      />
```

### version of react-native-gifted-charts

1.4.45

### React Native version

0.74.3

### Platforms

Android, iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @litofish 👋
Thanks for reporting this issue. It has been fixed from versions `1.4.46` onwards.

I have added a prop named `stripOverDataPoints` to Line charts. If set true, the vertical strip appears over the data points, else it appears beneath the data points. Its default value is false.

Please use the latest version of the library.

**Comment by litofish** [comment]
@Abhinandan-Kushwaha I just upgraded and unfortunately this still isn't working for me :(

I am seeing the prop and when I set `stripOverDataPoints={true}` it correctly moved the strip over all of them but when I set `stripOverDataPoints={false}` it is still overlapping all but one of the datapoints
<img width="350" alt="Screenshot 2024-10-21 at 1 41 43 PM" src="https://github.com/user-attachments/assets/f21ea70d-033b-4d94-b97e-e13661b990e1">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @litofish Can you share your code and data, so that I can run it?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @litofish I have published [version 1.4.47](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/releases/tag/v1.4.47) with slight fixes related to the `stripOverDataPoints` prop.

Please use the latest version of the library.

**Comment by litofish** [comment]
@Abhinandan-Kushwaha Thank you! That fixed it!
